// <auto-generated />
using System;
using HomeGuard.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeGuard.Infrastructure.Migrations
{
    [DbContext(typeof(HomeGuardDbContext))]
    partial class HomeGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("HomeGuard.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.BlobEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextCloudPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ServiceRecordId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WarrantyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRecordId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("WarrantyId");

                    b.HasIndex("OwnerEntityId", "OwnerEntityType");

                    b.ToTable("BlobEntries");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.PasskeyCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<uint>("SignCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.ScheduledJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RunAfter")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationKey");

                    b.HasIndex("Status", "RunAfter");

                    b.ToTable("ScheduledJobs");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.ServiceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NextServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdometerReading")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceProvider")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ServiceRecords");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleCalendarEventId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Warranties");
                });

            modelBuilder.Entity("HomeGuard.Infrastructure.Notifications.PushSubscriptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("HomeGuard.Infrastructure.Persistence.ProcessedOperation", b =>
                {
                    b.Property<Guid>("ClientOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AckJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientOperationId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("ProcessedOperations");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.BlobEntry", b =>
                {
                    b.HasOne("HomeGuard.Domain.Entities.Equipment", null)
                        .WithMany("Attachments")
                        .HasForeignKey("OwnerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeGuard.Domain.Entities.ServiceRecord", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ServiceRecordId");

                    b.HasOne("HomeGuard.Domain.Entities.Warranty", null)
                        .WithMany("Attachments")
                        .HasForeignKey("WarrantyId");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.PasskeyCredential", b =>
                {
                    b.HasOne("HomeGuard.Domain.Entities.AppUser", null)
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.ServiceRecord", b =>
                {
                    b.HasOne("HomeGuard.Domain.Entities.Equipment", null)
                        .WithMany("ServiceRecords")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("HomeGuard.Domain.ValueObjects.NotificationRule", "NotificationRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Offset")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("ServiceRecordId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ServiceRecordId");

                            b1.ToTable("ServiceRecords_NotificationRules");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRecordId");
                        });

                    b.Navigation("NotificationRules");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.Warranty", b =>
                {
                    b.HasOne("HomeGuard.Domain.Entities.Equipment", null)
                        .WithMany("Warranties")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("HomeGuard.Domain.ValueObjects.NotificationRule", "NotificationRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsEnabled")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Offset")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("WarrantyId")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("WarrantyId");

                            b1.ToTable("Warranties_NotificationRules");

                            b1.WithOwner()
                                .HasForeignKey("WarrantyId");
                        });

                    b.OwnsOne("HomeGuard.Domain.ValueObjects.DateRange", "Period", b1 =>
                        {
                            b1.Property<Guid>("WarrantyId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("End")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PeriodEnd");

                            b1.Property<string>("Start")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PeriodStart");

                            b1.HasKey("WarrantyId");

                            b1.ToTable("Warranties");

                            b1.WithOwner()
                                .HasForeignKey("WarrantyId");
                        });

                    b.Navigation("NotificationRules");

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ServiceRecords");

                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.ServiceRecord", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("HomeGuard.Domain.Entities.Warranty", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
